### ISSUE TITLE
Overloading errors in examples

### ISSUE THREAD

**Issue by miditant** [SimpleHacks/QDEC#7] opened 2022-02-04 23:24 UTC
The examples won't compile for me on the Arduino 1.8.19 IDE unless I fix them up.

error: call of overloaded 'QDecoder(const int&, const int&, bool)' is ambiguous

if I modify:
const int ROTARY_PIN_A = 3; 
const int ROTARY_PIN_B = 2;
to
int16_t ROTARY_PIN_A = 3; 
int16_t ROTARY_PIN_B = 2;

compiles just fine, at least on the first two examples.

**Comment by ingo-debus** [comment] 2022-03-29 16:00
I have the same issue when the target board is set to Arduino MKRZERO. However, when the target is set to Arduino Uno, at least the first example compiles with no errors. That's probably because on Due and SAMD based boards ints store 4 bytes (see https://www.arduino.cc/reference/en/language/variables/data-types/int/).

**Comment by thenderson** [comment] 2022-05-16 19:45
Same issue here when compiling for an ESP32. In my case, I had to change the variable types to uint16_t to get it to compile without errors.

**Comment by henrygab** [comment] 2022-08-23 19:39
First, thank you for reporting this.   I also apologize for the delay in responding.

The easiest workaround is to use the templated version of the QDEC class, which uses `uint32_t` to store the pins.

This **_doesn't resolve_** this issue, which is that the examples don't compile on all BSPs (board support packages), but I mention it if you just want to play with the code more.

<details><summary>root cause analysis</summary><P/>

At its core, the fundamental issue is that the Arduino ecosystem did not define the data type that should be used for a `pin`.  The original Arduino boards simply defined them as type `int`.  Then, some boards support packages (BSPs) started defining this as `unsigned int` (which is why there's overloads taking either `int16_t` or `uint16_t`).

Early 32-bit MCUs had hardware modules that could offload the detection and processing of QDECs ... see, for example, the Nordic nRF52 series of boards.  Thus, this wasn't seen as a major issue when the library was written, as using the hardware modules is more efficient.  In other words, support for 32-bit `int` is a "new feature" ... as relates to this library.

</details><HR/>
<details><summary>Example code ... options</summary><P/>

The longer goal is for the example code to compile, regardless of which BSP it is being used on.  This means that it should work regardless of the size of `int` on that platform (within C++ restrictions).  The variables affecting this are all potentially affected by the BSP in use:

1. Definition of `pinMode()`; Specifically, the data type for the first parameter.
2. The version of C++ used to compile (C++03? C++11? C++14? etc.)

Item 1 defines the "correct" data type to be used to store a pin number.  This is important because some BSPs require an unsigned data type, while other BSPs require a signed data type.

Item 2 essentially limits the ability to detect the data type to very basic C++ features.  For example, no using boost, no c++14 or later features, etc.

See https://stackoverflow.com/questions/43526647/decltype-of-function-parameter as an example of the ugliness that might be needed, all caused by the simple oversight of not having a well-defined name for BSPs to define the data type for pins....

</details><HR/>

Options:

1. Change the example to use a #define for the pin number.  Yes, this "fixes" the issue, but only by avoiding it ... the compiler then infers the data type at **_each_** place it is used ... with no requirement that the type remains the same ... which may have unexpected results.

2. Add code to the header that handles the various size of `int` / `unsigned int`. 

3. `<tbd>`

**Comment by henrygab** [comment] 2022-09-20 21:37
FYI - I now have a branch with a workflow working.  It properly shows that compilation on at least one BSP works fine (`arduino:avr:uno`), while it will fail with your indicated error on BSP `arduino:samd:mkrzero`.

Having this github action configured will help ensure (at least) compilation of examples, and implicitly document those platforms that are known to build successfully.

**Comment by henrygab** [comment] 2022-09-27 19:50
@miditant , @ingo-debus -- before I push v2.0.0 out the door, I would prefer your confirmation that the library works.

The code is in branch [v2_beta](https://github.com/SimpleHacks/QDEC/tree/v2_beta).  It will show library properties as 2.0.0.

If I don't hear of any problems in the next couple days, I will push that major version update.

NOTE: this is a major version update, because it technically has breaking changes.  That said, the library should now work for all ArduinoCore-API based platforms, including the ones you mentioned.

**Comment by henrygab** [comment] 2022-10-11 06:25
This is fixed in the `2.0.0-beta` release.

**Closed by henrygab** 2022-10-11 06:25 UTC
Labels: enhancement
